name: CI workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Built test sites
      run: |
        bundle exec jekyll build --config _test/_config-version-1.yml --destination ./_test-site-1
        bundle exec jekyll build --config _test/_config-version-2.yml --destination ./_test-site-2
    - name: Run tests
      run: |
        bundle exec htmlproofer ./_test-site-1 --disable-external
        bundle exec htmlproofer ./_test-site-2 --disable-external

  ci-skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: ci-skip-step
        uses: mstachniuk/ci-skip@v1
        with:
          commit-filter: '[skip ci]'

  publish-gh-pages:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{secrets.ADMIN_TOKEN}}
      USER_NAME: lexamo
      USER_EMAIL: lexamo.liu@gmail.com
      PUBLISH_DIR: ./_site
    steps:
      - name: Upload to ph-pages
        run: |
          cd $PUBLISH_DIR
          git init
          git config --local user.name $USER_NAME
          git config --local user.email $USER_EMAIL
          git status
          git remote add origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add --all
          git commit -m 'deploy to Github pages'
          git push origin gh-pages -f
          echo 🤘 deploy gh-pages complete.
